export {default as Header} from '@/components/header/Header'
export { default as Slider} from '@/components/slider/Slider'
export {default as Prediction} from '@/components/predictCTA/PredictCTA'
export {default as Results} from '@/components/resultsSec/ResultsSec'
export {default as Motto} from '@/components/mottoSec/MottoSec'
export {default as CardGroup} from '@/components/cards/CardGroup'
export {default as Card} from '@/components/cards/Card'